"""Claude Code hook handlers.

Hooks are what make the deterministic operations automatic and the gates
non-optional. The division of labour matters: `sync` runs constantly and
tolerantly *during* a turn, and `validate` runs once at the end and strictly.

Every handler is a **silent no-op outside a szsdlc project**, so the plugin is
harmless installed globally. That is not politeness — a hook that errors in a
repo which has never heard of szsdlc is a hook people uninstall.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from .errors import EXIT_OK

#: Claude Code reads exit 2 on a PreToolUse or Stop hook as "block, and show
#: the user what stderr said".
EXIT_BLOCK = 2


def read_payload(stream: Any = None) -> dict[str, Any]:
    """The hook's JSON input. A malformed payload is treated as no payload."""
    stream = stream if stream is not None else sys.stdin
    try:
        raw = stream.read()
    except Exception:  # pragma: no cover - stdin closed
        return {}
    if not raw or not raw.strip():
        return {}
    try:
        loaded = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def edited_path(payload: dict[str, Any]) -> Path | None:
    tool_input = payload.get("tool_input") or {}
    for key in ("file_path", "path", "notebook_path"):
        value = tool_input.get(key)
        if value:
            return Path(str(value))
    return None


def _session(start: Path | str | None):
    """Load the project, or None when there isn't one.

    Deliberately swallows everything: a hook must not be the thing that breaks
    a session, and whatever went wrong will be said properly the next time the
    user runs a command themselves.
    """
    from .cli import Session
    from .errors import SzsdlcError

    try:
        return Session(str(start) if start else None)
    except SzsdlcError:
        return None
    except Exception:  # pragma: no cover - defensive
        return None


def _emit(event: str, context: str) -> None:
    json.dump({"hookSpecificOutput": {"hookEventName": event,
                                      "additionalContext": context}}, sys.stdout)
    sys.stdout.write("\n")


# ---------------------------------------------------------------------------
# SessionStart
# ---------------------------------------------------------------------------


def session_start(payload: dict[str, Any], cwd: str | None = None) -> int:
    """Stdout enters the model's context, so a session begins knowing the state.

    This is the counters block earning its keep: a handful of tokens that says
    what is in flight and what is wrong, instead of the model searching.
    """
    from . import context as context_module
    from .graph import Graph

    session = _session(cwd or payload.get("cwd"))
    if session is None:
        return EXIT_OK

    graph = Graph(session.config, session.store, session.ids)
    built = context_module.build(session.config, session.store, graph)
    rendered = context_module.render(built)
    if rendered.strip():
        print(rendered)
    return EXIT_OK


# ---------------------------------------------------------------------------
# PreToolUse — Edit|Write
# ---------------------------------------------------------------------------


def pre_edit(payload: dict[str, Any], cwd: str | None = None) -> int:
    """Refuse edits to generated files, and inject the standards that apply.

    Both halves are the same idea: the convention governing a file arrives at
    the moment it is edited, and never before. A convention that depends on the
    agent remembering to look it up is not a convention.
    """
    from . import render as render_module
    from . import standards as standards_module

    path = edited_path(payload)
    if path is None:
        return EXIT_OK

    session = _session(cwd or payload.get("cwd") or path.parent)
    if session is None:
        return EXIT_OK

    if path.is_file():
        try:
            text = path.read_bytes().decode("utf-8", "replace")
        except OSError:  # pragma: no cover - unreadable target
            text = ""
        if render_module.is_generated(text):
            source = _source_hint(session, path)
            print(f"{path.name} is generated by szsdlc and must not be edited.",
                  file=sys.stderr)
            print(f"Fix: edit {source}, then run szsdlc sync", file=sys.stderr)
            return EXIT_BLOCK

    matched = standards_module.matching(session.config, [path])
    if matched:
        # 200–500 tokens for the conventions that apply here, rather than every
        # convention in the project on every turn.
        blocks = [f"## {standard.name}\n{standard.body}" for standard in matched]
        _emit("PreToolUse", "szsdlc standards for this path:\n\n"
              + "\n\n".join(blocks))
    return EXIT_OK


def _source_hint(session, path: Path) -> str:
    """Which view or record produces this file — named, not guessed."""
    for name in session.config.views:
        if session.config.view_path(name) == path:
            return f"the entities behind the {name!r} view"
    for name in session.config.records:
        if session.config.record_path(name) == path:
            return session.config.records[name].data
    return "its source"


# ---------------------------------------------------------------------------
# PostToolUse — Edit|Write
# ---------------------------------------------------------------------------


def post_edit(payload: dict[str, Any], cwd: str | None = None) -> int:
    """Regenerate when a source file changed. Tolerant, silent, every time."""
    from . import render as render_module
    from .graph import Graph

    path = edited_path(payload)
    if path is None:
        return EXIT_OK

    session = _session(cwd or payload.get("cwd") or path.parent)
    if session is None:
        return EXIT_OK

    if not _is_source(session, path):
        return EXIT_OK

    try:
        graph = Graph(session.config, session.store, session.ids)
        render_module.sync(session.config, session.store, graph)
    except Exception:  # pragma: no cover - never break a turn over a redraw
        pass
    return EXIT_OK


def _is_source(session, path: Path) -> bool:
    candidate = path if path.is_absolute() else (session.config.root / path)
    try:
        candidate = candidate.resolve()
    except OSError:  # pragma: no cover
        return False

    watched = [session.config.dir_for(t) for t in session.config.entity_types.values()]
    watched += [session.config.roadmaps_dir, session.config.standards_dir]
    watched += [(session.config.root / spec.data).parent
                for spec in session.config.records.values()]

    for directory in watched:
        try:
            candidate.relative_to(directory)
        except ValueError:
            continue
        return True
    return False


# ---------------------------------------------------------------------------
# Stop
# ---------------------------------------------------------------------------


def stop(payload: dict[str, Any], cwd: str | None = None) -> int:
    """The single enforcement point: strict, once, at the end of the turn."""
    from . import validate as validate_module
    from .graph import Graph

    session = _session(cwd or payload.get("cwd"))
    if session is None:
        return EXIT_OK

    graph = Graph(session.config, session.store, session.ids)
    findings = validate_module.run(session.config, session.store, graph)
    errors = [f for f in findings if f.is_error]
    if not errors:
        return EXIT_OK

    print(f"szsdlc validate found {len(errors)} "
          f"error{'s' if len(errors) != 1 else ''}:", file=sys.stderr)
    for finding in errors[:10]:
        print(f"  {finding.ref}  {finding.message}"
              + (f" — {finding.fix}" if finding.fix else ""), file=sys.stderr)
    if len(errors) > 10:
        print(f"  … {len(errors) - 10} more — szsdlc validate", file=sys.stderr)
    return EXIT_BLOCK


HANDLERS = {
    "session-start": session_start,
    "pre-edit": pre_edit,
    "post-edit": post_edit,
    "stop": stop,
}


def dispatch(event: str, stream: Any = None, cwd: str | None = None) -> int:
    handler = HANDLERS.get(event)
    if handler is None:  # pragma: no cover - argparse constrains the choices
        return EXIT_OK
    return handler(read_payload(stream), cwd)
