"""Rendering: every index, board, register and back-link, generated from source.

`sync` is deliberately **permissive**. It must succeed against a broken graph,
because intermediate states are legitimately invalid — an entity exists before
it is linked, is linked before it is scheduled — and because views are most
needed exactly when something is wrong. Rendering asks only "can I load and
draw this?"; `validate` asks "is this project coherent?".

That is why a dangling reference renders as `WI-0420 (missing)` and an
unparseable file appears in the view with its path. Dropping broken edges would
let `sync` conceal precisely what `validate` exists to surface.

There is no `--check` flag. Staleness is a `validate` rule implemented with the
:func:`compare` primitive below, so CI and pre-commit ask one question, not two.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

import jinja2
import yaml
from jsonschema import Draft202012Validator

from .config import Config
from .context import age_days, first_unchecked
from .errors import BadInput
from .graph import Graph
from .model import EntityStore
from .roadmap import Roadmap, load_all as load_roadmaps
from .text import clip

BANNER = "<!-- GENERATED by szsdlc — do not edit; edit the source and rerun `szsdlc sync`. -->"
HASH_PREFIX = "<!-- content-hash: "
HASH_SUFFIX = " -->"


@dataclass(frozen=True)
class Rendered:
    """One generated file, in memory. Nothing here has touched the disk yet."""

    name: str
    path: Path
    body: str

    @property
    def content(self) -> str:
        """Banner, hash, then the body.

        The hash digests the *rendered body*, which is what makes a hand-edit
        distinguishable from staleness: a mismatch means somebody typed into a
        generated file, while a matching hash over different content means the
        sources moved on. A hash of the inputs could only ever tell you the
        second thing.
        """
        digest = hashlib.sha256(self.body.encode("utf-8")).hexdigest()[:16]
        return f"{BANNER}\n{HASH_PREFIX}sha256:{digest}{HASH_SUFFIX}\n\n{self.body}"

    def matches_disk(self) -> bool:
        if not self.path.is_file():
            return False
        return self.path.read_bytes().decode("utf-8", "replace") == self.content

    def write(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_bytes(self.content.encode("utf-8"))


def is_generated(text: str) -> bool:
    """Does this content carry the generated banner? Used by the edit hook."""
    return text.lstrip().startswith(BANNER)


def stored_hash(text: str) -> str | None:
    for line in text.splitlines()[:5]:
        if line.startswith(HASH_PREFIX) and line.endswith(HASH_SUFFIX):
            return line[len(HASH_PREFIX):-len(HASH_SUFFIX)]
    return None


def hand_edited(text: str) -> bool:
    """True when a generated file's body no longer matches its own hash."""
    declared = stored_hash(text)
    if declared is None:
        return False
    _, _, body = text.partition("\n\n")
    actual = "sha256:" + hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]
    return declared != actual


class Renderer:
    """Renders every configured view and record from one loaded graph."""

    def __init__(self, config: Config, store: EntityStore, graph: Graph,
                 roadmaps: dict[str, Roadmap] | None = None):
        self.config = config
        self.store = store
        self.graph = graph
        self.roadmaps = roadmaps if roadmaps is not None else load_roadmaps(config)
        self.environment = self._environment()

    def _environment(self) -> jinja2.Environment:
        bundled = resources.files("szsdlc").joinpath("templates")
        environment = jinja2.Environment(
            loader=jinja2.ChoiceLoader([
                # A project override wins; the bundled default is the fallback.
                jinja2.FileSystemLoader(str(self.config.templates_dir)),
                jinja2.FileSystemLoader(str(bundled)),
            ]),
            autoescape=False,
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
            undefined=jinja2.StrictUndefined,
        )
        environment.globals.update(
            config=self.config,
            store=self.store,
            graph=self.graph,
            roadmaps=self.roadmaps,
            entities=sorted(self.store, key=lambda e: (e.id.prefix, e.id.number)),
            unparseable=self.store.unparseable,
            duplicates=self.store.duplicates,
            types_with=self.config.types_with,
            of_type=self.store.of_type,
            derived=self.graph.derived,
            children=self.graph.children,
            sources=self.graph.sources,
            targets=self.graph.targets,
            age_days=age_days,
            next_task=first_unchecked,
            relative=lambda path: self._relative(path),
        )
        # A title may be derived from body text, so it is exactly as long as
        # whoever captured the thought felt like being. Unclipped, one such
        # entity turns a markdown table into a single unreadable row.
        environment.filters["clip"] = clip
        return environment

    def _relative(self, path: Path | str) -> str:
        try:
            return Path(path).resolve().relative_to(self.config.root).as_posix()
        except ValueError:
            return str(path)

    # -- views --------------------------------------------------------------

    def view(self, name: str) -> Rendered:
        spec = self.config.views[name]
        template = self.environment.get_template(spec.template)
        body = template.render(view=spec, name=name)
        return Rendered(name=name, path=self.config.view_path(name), body=body)

    def record(self, name: str) -> Rendered:
        """A project-defined dataset rendered through its own template.

        The generic mechanism for any tracked table a project needs. Nothing
        project-specific ships built in; this is how it gets added without
        touching the framework.
        """
        spec = self.config.records[name]
        data_path = self.config.root / spec.data
        if not data_path.is_file():
            raise BadInput(
                f"record {name!r}: {self._relative(data_path)} does not exist.",
                fix=f"create {self._relative(data_path)}",
            )

        try:
            data = yaml.safe_load(data_path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            problem = getattr(exc, "problem", None) or "invalid YAML"
            raise BadInput(
                f"record {name!r}: {self._relative(data_path)}: {problem}.",
                fix=f"correct {self._relative(data_path)}",
            ) from None

        if spec.schema:
            schema_path = self.config.root / spec.schema
            schema = json.loads(schema_path.read_text(encoding="utf-8"))
            errors = sorted(Draft202012Validator(schema).iter_errors(data),
                            key=lambda e: list(e.absolute_path))
            if errors:
                where = ".".join(str(p) for p in errors[0].absolute_path) or "(root)"
                raise BadInput(
                    f"record {name!r}: {where}: {errors[0].message}",
                    fix=f"correct {self._relative(data_path)}",
                )

        template = self.environment.get_template(spec.template)
        body = template.render(record=spec, name=name, data=data)
        return Rendered(name=name, path=self.config.record_path(name), body=body)

    def all(self) -> list[Rendered]:
        return ([self.view(name) for name in self.config.views]
                + [self.record(name) for name in self.config.records])


def compare(rendered: list[Rendered]) -> list[Rendered]:
    """Which generated files would differ from what is on disk.

    The primitive `sync` uses to avoid pointless writes and `validate` borrows
    for its staleness rule — one implementation, so the two can never disagree
    about what "stale" means.
    """
    return [item for item in rendered if not item.matches_disk()]


def sync(config: Config, store: EntityStore, graph: Graph,
         roadmaps: dict[str, Roadmap] | None = None) -> list[Rendered]:
    """Regenerate everything, writing only what changed. Never validates."""
    renderer = Renderer(config, store, graph, roadmaps)
    changed = compare(renderer.all())
    for item in changed:
        item.write()
    return changed
